[package]
name = "eduma"
version = "0.1.0"
authors = ["Dylan Jessen <djessen@calpoly.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
printpdf = "0.3.4"
